version: '3'
services:
  
  clickhouse:
    image: pycontribs/centos:7
    container_name: clickhouse
    restart: unless-stopped
    entrypoint: "sleep infinity"
    ports:
      - 8123:8123
    
  vector:
    image: pycontribs/ubuntu
    container_name: vector
    restart: unless-stopped
    entrypoint: "sleep infinity"
    ports:
      - 8686:8686

